### ISSUE TITLE
TestACLBearer#test_bearer_token_compound_operations fails

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-testcases#667]
## Expected Behavior
Test pass.

## Current Behavior
Test fail.

## Possible Solution
Fix the bug.

## Steps to Reproduce (for bugs)
https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/832-1695916423/index.html#suites/06e488d665f58dfc1e53a2c40757bcdb/ed1c2dfbfc8419c1/

## Context
It seems to be trying to make a SEARCH that should fail (unfortunately, bearer token itself is not available from logs), either for USER, or for OTHERS. It's certainly disable in the EACL for OTHERS.

## Regression
Maybe.

**Comment by carpawell** [comment]
Transferred from the node repo. It does not look like a storage issue. A bearer token attached allows SEARCH and a node does it.
The issue is not stable: it was ok [here](https://github.com/nspcc-dev/neofs-node/actions/runs/6185388307/job/16790891798). BUT it is also OK now if choose the same _test_ repo version (`7af282f90f32e80301a146c91d9db49ee2bcb0b8`) and _any_ node.

Near this issue, i would also pay attention to the fact how a bearer appears for the tests: https://github.com/nspcc-dev/neofs-testcases/blob/f84893982af2d1d7d52cb84b9756a3252bdb2499/robot/resources/lib/python_keywords/acl.py#L189. It uses container's eACL as a base and then just appends it with the test rules. Why?

Any issuer fixer, please, read how bearer token [should work](https://github.com/nspcc-dev/neofs-api/blob/1424834f743842b88e02ec6ac79c64ef2d2d3e75/acl/types.proto#L180-L181) and ask me if any questions appear. A review request of mine will be also appreciated.

**Comment by roman-khimov** [comment]
Doesn't reproduce any more.
